version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

api:
  build:
    context: ../..          # repo root
    dockerfile: infra/docker/api.Dockerfile
  env_file:
    - ../../apps/api/.env
  environment:
    ASPNETCORE_URLS: http://+:8080
    ConnectionStrings__Default: Host=postgres;Username=postgres;Password=postgres;Database=lms
    STORAGE__ENDPOINT: http://minio:9000
    STORAGE__ACCESS_KEY: admin
    STORAGE__SECRET_KEY: password
    STORAGE__BUCKET: scorm
  depends_on:
    - postgres
    - redis
    - minio
  ports:
    - "8080:8080"

web:
  build:
    context: ../..
    dockerfile: infra/docker/web.Dockerfile
  env_file:
    - ../../apps/web/.env
  ports:
    - "5173:5173"

worker:
  build:
    context: ../..
    dockerfile: infra/docker/worker.Dockerfile
  env_file:
    - ../../apps/worker/.env
  depends_on:
    - postgres
    - redis
    - minio


volumes:
  pgdata:
  miniodata:
