services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
  api:
    build: ../../apps/api
    env_file: ../../apps/api/.env
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8080:8080"
  worker:
    build: ../../apps/worker
    env_file: ../../apps/worker/.env
    depends_on:
      - postgres
      - redis
      - minio
  web:
    build: ../../apps/web
    env_file: ../../apps/web/.env
    ports:
      - "5173:5173"
